# config.yaml for XGBoostLocalPipeline

project_setup:
  experiment_name: "PRE_XGB_Local_Run"   # Base name for the experiment; "_local" will be appended by the pipeline script for output folders
  target_variable: "pre"
  random_seed: 42

data:
  raw_data_path: "../../data/full.csv"      # Path to your full dataset, relative to this config file's location
  time_column: "time"
  lat_column: "lat"
  lon_column: "lon"
  predictor_columns: [                # List of raw predictor columns from your CSV
      'tmp', 'dtr', 'cld', 'tmx', 
      'tmn', 'wet', 'vap', 'soi', 
      'dmi', 'pdo', 'nino4', 
      'nino34', 'nino3', 'pet' # Added pre and pet as potential predictors
    ]
  train_end_date: "2018-12-31"        # Last date for the training set
  validation_end_date: "2020-12-31"   # Last date for the validation set (test set starts after this)

feature_engineering:
  # columns_to_lag: [] # If empty or not present, will be auto-populated with target_variable + predictor_columns
  lag_periods: [1, 2, 3, 6, 9, 12]    # Lag periods in months
  date_features_to_extract: ['month', 'year'] # e.g., month, year, dayofweek, quarter

scaling:
  method: "robust"                    # Scaling method: "robust", "standard", or "minmax"
  scaler_filename: "local_robust_scaler.joblib" # Base filename for saved scalers (location identifier will be prepended)

model_params:
  # Parameters in 'global_xgboost' will be used for *each* local XGBoost model
  global_xgboost: 
    objective: "reg:squarederror"
    eval_metric: "rmse"
    n_estimators: 100               # Initial number of estimators
    learning_rate: 0.1
    max_depth: 5
    subsample: 0.8
    colsample_bytree: 0.8
    model_filename: "local_xgb_model.json" # Base filename for saved models (location identifier will be prepended)
                                           # If not provided, defaults to 'xgboost_model.json' in the script
model_params:
  optuna_trials: 10
paths:
  models_base_dir: "../../models_saved"
  output_base_dir: "../../run_outputs"

results:
  # Filename for the aggregated metrics JSON file from all local models
  metrics_filename: "all_local_models_evaluation_metrics.json"
  per_location_predictions_dir: "per_location_full_predictions" # Subdirectory within the experiment's output_base_dir
  per_location_prediction_filename_suffix: "_full_pred.csv"   # Suffix for each location's prediction file
  # config_filename: "config_used_for_run.yaml" # Default in global pipeline, not explicitly used by local for saving itself
  # feature_importance_filename: "feature_importance.png" # Not generated by local pipeline class
