# config_CNN3D_SPEI.yaml
# Configuration file for the CNN3DPipeline

project_setup:
  experiment_name: "cnn2dlstm_SPEI"
  target_variable: "spei"
  random_seed: 42

gridding:
  fixed_step: 0.5 
data:
  raw_data_path: "data/full.csv"
  time_column: "time"
  lat_column: "lat"
  lon_column: "lon"
  predictor_columns: [
      'tmp', 'dtr', 'cld', 'tmx', 'tmn', 'wet', 
      'vap', 'soi', 'dmi', 'pdo', 'nino4', 
      'nino34', 'nino3', 'pet', 'pre', 'spei'
  ]
  features_to_grid: [
    'tmp', 'dtr', 'cld', 'tmx', 
    'tmn', 'wet', 'vap', 'soi', 
    'dmi', 'pdo', 'nino4', 
    'nino34', 'nino3', 'pre', 'pet', 'spei'
  ]
  train_end_date: "2017-12-31"
  validation_end_date: "2020-12-31"
  scaler_path: "models_saved/CNN3D_SPEI_Run/cnn3d_scaler.joblib"
scaling:
  method: "robust"
  scaler_filename: "cnn3d_scaler.joblib"

cnnlstm_params:
  batch_size: 8
  n_steps_in: 12
  hidden_cnn: 16
  kernel_size: 3
  lstm_hidden_size: 64
  lstm_layers: 1
  dropout: 0.2
  learning_rate: 0.001
  use_layernorm: true
  max_epochs: 500
  patience: 30
  max_epochs_tune: 100  # for Optuna tuning loop

optuna_tuning:
  n_trials: 100
  search_space:
    learning_rate: {low: 1.0e-5, high: 1.0e-2, log: true}
    hidden_channels: [8, 16, 32]
    n_conv_layers: {low: 1, high: 3}
    batch_size: [4, 8, 16]
    kernel_size: {low: 2, high: 5}

paths:
  models_base_dir: "models_saved"
  results_dir: "run_outputs"

results:
  metrics_filename: "cnn2dlstm_model_metrics.json"
  predictions_filename: "cnn2dlstm_full_predictions.csv"
  tensorboard_log_dir: "tensorboard_logs"
  config_filename: "config_used_for_run.yaml"
