# config_ConvLSTM_EncoderDecoder.yaml
# Configuration file for the Encoder-Decoder ConvLSTM model

project_setup:
  experiment_name: "SPEI_ConvLSTM_EncoderDecoder_Run"
  target_variable: "spei"
  random_seed: 42

data:
  raw_data_path: "data/full.csv"
  time_column: "time"
  lat_column: "lat"
  lon_column: "lon"
  features_to_grid: [
      'spei', 'tmp', 'dtr', 'cld', 'tmx', 
      'tmn', 'wet', 'vap', 'soi', 
      'dmi', 'pdo', 'nino4', 
      'nino34', 'nino3', 'pre', 'pet'
    ]
  train_end_date: "2017-12-31"
  validation_end_date: "2020-12-31"

gridding:
  fixed_step: 0.5 

sequence_params:
  # n_steps_in is pre_seq_length for the new model
  n_steps_in: 12      
  # n_steps_out is aft_seq_length, how many steps to predict
  n_steps_out: 1 # You can experiment with predicting more steps, e.g., 3 or 6

convlstm_params:
  batch_size: 16       
  
  trainer:
    max_epochs: 200
    patience_for_early_stopping: 30
    accelerator: "auto"
    enable_progress_bar: True
  
  tuning:
    n_trials: 1
    learning_rate: {low: 1.0e-5, high: 1.0e-5, log: True}
    # For this model, hidden_dim is a list. We will tune the size for all layers together.
    hidden_dim_size: {choices: [64]} 
    # n_layers and hidden_dim_size will be used to construct the hidden_dim list
    n_layers: {low: 2, high: 3}
    kernel_size: {choices: [3, 5]} # A single kernel size for all layers
        
paths:
  models_base_dir: "models_saved" 

results:
  output_base_dir: "run_outputs" 
  metrics_filename: "global_convlstm_encdec_metrics.json"
  predictions_filename: "global_convlstm_encdec_full_predictions.csv"
  config_filename: "config_used_for_run.yaml"

