paths:
  run_output_dir: runs/cam_convlstm
  raw_data: ../data/processed/full_scaled.csv        # <- point to this file

grid:
  height: 10                      # update as needed
  width: 10
  lat_range: [6.25, 20.25]        # based on your latitudes
  lon_range: [99.75, 105.25]      # based on your longitudes

data:
  raw_data_path: ../data/processed/full_scaled.csv        # <- point to this file
  scaler_path_pre: "../data/processed/robust_scaler_pre.joblib"
  scaler_path_pet: "data/processed/robust_scaler_pet.joblib"
  time_column: "time"
  lat_column: "lat"
  lon_column: "lon"
  features_to_grid: [
      'tmp', 'dtr', 'cld', 'tmx', 
      'tmn', 'wet', 'vap', 'soi', 
      'dmi', 'pdo', 'nino4', 
      'nino34', 'nino3', 'pre', 'pet'
    ]
  train_end_date: "2017-12-31"
  validation_end_date: "2020-12-31"
gridding:
  fixed_step: 0.5 
sequence_params:
  n_steps_in: 12      
  n_steps_out: 1  # Predict 3 time steps ahead
model:
  input_channels: 13              # num of input vars, e.g. tmp, dtr, ... (exclude spei)
seed: 42
feature_names:
  - tmp
  - dtr
  - cld
  - tmx
  - tmn
  - pre
  - wet
  - vap
  - soi
  - dmi
  - pdo
  - nino4
  - nino34

training:
  batch_size: 8
  epochs: 50
  learning_rate: 0.001

temporal:
  prediction_start: "2020-01"
  freq: "M"                     # daily if needed, or "M" for monthly
  output_steps: 12
